### PR TITLE
Updated styles button

### PR DESCRIPTION
**Pull request by BrunoLagoa**
Hello, If possible, would you like to add the tags to this pr, hacktoberfest, hacktoberfest-accepted. to participate in the event.

### CODE REVIEW

**Comment by BrunoLagoa** [comment]
Captura de Tela 2022-10-10 às 22 48 31

**Comment by abhinavkashyap061** [comment]
i have added the tags @BrunoLagoa . can you commit again it's giving conflicts

**Comment by BrunoLagoa** [comment]
Nice! Checking.

**Comment by BrunoLagoa** [comment]
@abhinavkashyap061 pr updated.

**Review by abhinavkashyap061 — APPROVED** [review]

**Comment by BrunoLagoa** [comment]
close #12

**Comment by BrunoLagoa** [comment]
adjustment has already been made in
https://github.com/abhinavkashyap061/todolist/pull/23

**Pull request merged**
